language: node_js

node_js:
  - "10"
before_install:
  - npm i -g npm@latest

notifications:
  email:
    on_success: always
    on_failure: always
language: node_js
node_js:
  - 'stable'
install: npm install
before_script:

script: npm run build
after_success: 